#ifndef QBF2ASP_QBF2ASP_AC_ENABLE_DECOMPOSITION_H_
#define QBF2ASP_QBF2ASP_AC_ENABLE_DECOMPOSITION_H_

#  ifdef ENABLE_DECOMPOSITION
#    undef ENABLE_DECOMPOSITION
#  endif // ENABLE_DECOMPOSITION

#  include <qbf2asp/ac_enable_decomposition.h>

#endif // QBF2ASP_QBF2ASP_AC_ENABLE_DECOMPOSITION_H_
